// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package models

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	// Password Пароль для аутентификации.
	Password string `json:"password"`

	// Username Имя пользователя для аутентификации.
	Username string `json:"username"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// Token JWT-токен для доступа к защищенным ресурсам.
	Token *string `json:"token,omitempty"`
}

// CoinHistoryField defines model for CoinHistoryField.
type CoinHistoryField struct {
	Received *RecivedField `json:"received,omitempty"`
	Sent     *SentField    `json:"sent,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Errors Сообщение об ошибке, описывающее проблему.
	Errors string `json:"errors"`
}

// InfoResponse defines model for InfoResponse.
type InfoResponse struct {
	CoinHistory *CoinHistoryField `json:"coinHistory,omitempty"`

	// Coins Количество доступных монет.
	Coins     *int            `json:"coins,omitempty"`
	Inventory *InventoryField `json:"inventory,omitempty"`
}

// InventoryField defines model for InventoryField.
type InventoryField = []InventoryItem

// InventoryItem defines model for InventoryItem.
type InventoryItem struct {
	// Quantity Количество предметов.
	Quantity int `json:"quantity"`

	// Type Тип предмета.
	Type string `json:"type"`
}

// RecivedField defines model for RecivedField.
type RecivedField = []RecivedItem

// RecivedItem defines model for RecivedItem.
type RecivedItem struct {
	// Amount Количество полученных монет.
	Amount int `json:"amount"`

	// FromUser Имя пользователя, который отправил монеты.
	FromUser string `json:"fromUser"`
}

// SendCoinRequest defines model for SendCoinRequest.
type SendCoinRequest struct {
	// Amount Количество монет, которые необходимо отправить.
	Amount int `json:"amount"`

	// ToUser Имя пользователя, которому нужно отправить монеты.
	ToUser string `json:"toUser"`
}

// SentField defines model for SentField.
type SentField = []SentItem

// SentItem defines model for SentItem.
type SentItem struct {
	// Amount Количество отправленных монет.
	Amount int `json:"amount"`

	// ToUser Имя пользователя, которому отправлены монеты.
	ToUser string `json:"toUser"`
}

// PostApiAuthJSONRequestBody defines body for PostApiAuth for application/json ContentType.
type PostApiAuthJSONRequestBody = AuthRequest

// PostApiSendCoinJSONRequestBody defines body for PostApiSendCoin for application/json ContentType.
type PostApiSendCoinJSONRequestBody = SendCoinRequest
