# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Start PostgreSQL for test
      run: |
        docker compose up db-test -d
        for i in {1..10}; do
          if pg_isready -h localhost -p 5050 -U postgres; then
            echo "PostgreSQL is ready!"
            exit 0
          fi
          echo "Waiting for PostgreSQL..."
          sleep 3
        done
        echo "PostgreSQL failed to start!"
        exit 1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
